from backend.db.database import SessionLocal
from backend.models.models import Product

# List of products as plain dicts so we can update or create by seo_slug
PRODUCTS = [
    {
        "owner_id": None,
        "sku": "SKU-AURORA-TOTE-001",
        "name": "Aurora Leather Tote",
        "brand": "Maison Luma",
        "category": "Bags",
        "description_md": "Minimalist calf-leather tote with reinforced stitching.",
        "price_cents": 45000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "aurora-leather-tote",
        "hero_image_url": "https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-NOIR-COAT-002",
        "name": "Midnight Trench Coat",
        "brand": "Noir Atelier",
        "category": "Coats",
        "description_md": "Structured trench coat crafted for all-year elegance.",
        "price_cents": 69000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "midnight-trench-coat",
        "hero_image_url": "https://images.pexels.com/photos/7671166/pexels-photo-7671166.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-LUNE-HEEL-003",
        "name": "Celeste Heel 90",
        "brand": "Lune",
        "category": "Shoes",
        "description_md": "Elegant 90 mm heel for evening wear.",
        "price_cents": 52000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "celeste-heel-90",
        "hero_image_url": "https://images.pexels.com/photos/5704849/pexels-photo-5704849.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-MARIN-BLAZER-004",
        "name": "Marin Tailored Blazer",
        "brand": "Atelier de Rivière",
        "category": "Jackets",
        "description_md": "Slim-cut blazer with textured wool weave.",
        "price_cents": 78000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "marin-tailored-blazer",
        "hero_image_url": "https://images.pexels.com/photos/5325913/pexels-photo-5325913.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-FIORA-DRESS-005",
        "name": "Fiora Silk Midi Dress",
        "brand": "Valente Milano",
        "category": "Dresses",
        "description_md": "Flowing pure-silk midi dress inspired by Italian summer nights.",
        "price_cents": 88000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "fiora-silk-midi-dress",
        "hero_image_url": "https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-ORION-SNEAKER-006",
        "name": "Orion Knit Sneakers",
        "brand": "Studio Arc",
        "category": "Shoes",
        "description_md": "Lightweight knit sneaker designed for comfort and style.",
        "price_cents": 32000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "orion-knit-sneakers",
        "hero_image_url": "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-POLARIS-SCARF-007",
        "name": "Polaris Cashmere Scarf",
        "brand": "Nord & Co.",
        "category": "Accessories",
        "description_md": "Handwoven cashmere scarf with a cloud-soft finish.",
        "price_cents": 26000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "polaris-cashmere-scarf",
        "hero_image_url": "https://images.pexels.com/photos/704977/pexels-photo-704977.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-ELARA-RING-008",
        "name": "Elara Gold Band",
        "brand": "Crescent Jewels",
        "category": "Jewellery",
        "description_md": "14k gold band with a minimalist sculpted profile.",
        "price_cents": 115000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "elara-gold-band",
        "hero_image_url": "https://images.pexels.com/photos/1653229/pexels-photo-1653229.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-SERA-PANTS-009",
        "name": "Sera Wide-Leg Trousers",
        "brand": "Atelier Soma",
        "category": "Trousers",
        "description_md": "Relaxed wide-leg trousers crafted from breathable viscose.",
        "price_cents": 54000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "sera-wide-leg-trousers",
        "hero_image_url": "https://images.pexels.com/photos/7679721/pexels-photo-7679721.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-ARCADIA-HAT-010",
        "name": "Arcadia Wool Fedora",
        "brand": "Maison d'Or",
        "category": "Accessories",
        "description_md": "Classic wool fedora reimagined with a modern silhouette.",
        "price_cents": 38000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "arcadia-wool-fedora",
        "hero_image_url": "https://images.pexels.com/photos/374675/pexels-photo-374675.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-LUMA-BELT-011",
        "name": "Luma Leather Belt",
        "brand": "Maison Luma",
        "category": "Accessories",
        "description_md": "Full-grain leather belt with a brushed metal buckle.",
        "price_cents": 22000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "luma-leather-belt",
        "hero_image_url": "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-NOIR-WOOL-012",
        "name": "Noir Wool Overcoat",
        "brand": "Noir Atelier",
        "category": "Coats",
        "description_md": "Double breasted wool overcoat with clean lines.",
        "price_cents": 71000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "noir-wool-overcoat",
        "hero_image_url": "https://images.pexels.com/photos/7671169/pexels-photo-7671169.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-RIVIERE-SKIRT-013",
        "name": "Riviera Pleated Skirt",
        "brand": "Atelier de Rivière",
        "category": "Skirts",
        "description_md": "Midi length pleated skirt with a subtle sheen.",
        "price_cents": 49000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "riviera-pleated-skirt",
        "hero_image_url": "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-VALENTE-BLOUSE-014",
        "name": "Valente Silk Blouse",
        "brand": "Valente Milano",
        "category": "Tops",
        "description_md": "Silk button up blouse with a relaxed drape.",
        "price_cents": 58000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "valente-silk-blouse",
        "hero_image_url": "https://images.pexels.com/photos/6311579/pexels-photo-6311579.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-ARC-TEE-015",
        "name": "Arc Studio Logo Tee",
        "brand": "Studio Arc",
        "category": "Tops",
        "description_md": "Organic cotton T shirt with tonal logo print.",
        "price_cents": 18000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "arc-studio-logo-tee",
        "hero_image_url": "https://images.pexels.com/photos/7671168/pexels-photo-7671168.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-NORD-GLOVES-016",
        "name": "Nord Cashmere Gloves",
        "brand": "Nord & Co.",
        "category": "Accessories",
        "description_md": "Ribbed cashmere gloves for cold days.",
        "price_cents": 24000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "nord-cashmere-gloves",
        "hero_image_url": "https://images.pexels.com/photos/374707/pexels-photo-374707.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-CRESCENT-NECK-017",
        "name": "Crescent Pendant Necklace",
        "brand": "Crescent Jewels",
        "category": "Jewellery",
        "description_md": "Fine chain necklace with a sculpted crescent pendant.",
        "price_cents": 98000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "crescent-pendant-necklace",
        "hero_image_url": "https://images.pexels.com/photos/1158438/pexels-photo-1158438.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-SOMA-SHORTS-018",
        "name": "Soma Tailored Shorts",
        "brand": "Atelier Soma",
        "category": "Shorts",
        "description_md": "High waist tailored shorts in soft twill.",
        "price_cents": 36000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "soma-tailored-shorts",
        "hero_image_url": "https://images.pexels.com/photos/7679657/pexels-photo-7679657.jpeg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-MAISON-LOAFER-019",
        "name": "Maison City Loafers",
        "brand": "Maison d'Or",
        "category": "Shoes",
        "description_md": "Polished leather loafers with a low stacked heel.",
        "price_cents": 54000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "maison-city-loafers",
        "hero_image_url": "https://images.pexels.com/photos/19090/pexels-photo.jpg?w=800",
    },
    {
        "owner_id": None,
        "sku": "SKU-AURORA-CROSSBODY-020",
        "name": "Aurora Crossbody Bag",
        "brand": "Maison Luma",
        "category": "Bags",
        "description_md": "Compact crossbody bag with adjustable strap and magnetic closure.",
        "price_cents": 42000,
        "currency": "GBP",
        "active": True,
        "seo_slug": "aurora-crossbody-bag",
        "hero_image_url": "https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?w=800",
    },
]


def seed_products() -> None:
    db = SessionLocal()
    try:
        for data in PRODUCTS:
            slug = data["seo_slug"]
            existing = db.query(Product).filter_by(seo_slug=slug).first()
            if existing:
                print(f"Updating existing product '{slug}' (id={existing.id})")
                for key, value in data.items():
                    setattr(existing, key, value)
            else:
                print(f"Creating new product '{slug}'")
                db.add(Product(**data))

        db.commit()
        print("Seed completed successfully.")
    except Exception as exc:
        db.rollback()
        print(f"Error while seeding products: {exc!r}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_products()
